version: '3'
services:

  ### Приложение

  wordpress:
    image: wordpress:fpm
    container_name: wp-wordpress
    restart: unless-stopped
    networks:
      - webapp
    depends_on:
      - database
    volumes:
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=password123!

  database:
    image: mysql:8
    container_name: wp-database
    restart: unless-stopped
    networks:
      - webapp
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password123!
      - MYSQL_ROOT_PASSWORD=rootpassword123!
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    image: nginx:alpine
    container_name: wp-nginx
    restart: unless-stopped
    networks:
      - webapp
      - prometheus
    depends_on:
      - wordpress
      - node_exporter
      - nginx_exporter
      - mysqld_exporter
      - php-fpm_exporter
      - blackbox_exporter
    ports:
      - 80:80
      - 8443:8443
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/htpasswd:/etc/nginx/.htpasswd
      - ./ssl:/etc/ssl

  ### Экспортеры приложения 

  node_exporter:
    image: prom/node-exporter:latest
    container_name: wp-node_exporter
    restart: unless-stopped
    networks:
      - webapp
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    command:
      - '--path.rootfs=/host'

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: wp-nginx_exporter
    restart: unless-stopped
    networks:
      - webapp
    command:
      - -nginx.scrape-uri=http://nginx:8080/stub_status

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: wp-mysqld_exporter
    restart: unless-stopped
    networks:
      - webapp
    depends_on:
      - database
    environment:
      - DATA_SOURCE_NAME=root:rootpassword123!@(database:3306)/wordpress

  php-fpm_exporter:
    image: hipages/php-fpm_exporter:latest
    container_name: wp-php-fpm_exporter
    restart: unless-stopped
    networks:
      - webapp
    depends_on:
      - wordpress
    environment:
      - PHP_FPM_SCRAPE_URI=tcp://wordpress:9000/status

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: wp-blackbox_exporter
    restart: unless-stopped
    networks:
      - webapp
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml

  ### Prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: ps-prometheus
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - prometheus
    ports:
      - 9090:9090
    volumes:
      - ./GAP-1/prometheus/:/etc/prometheus/
      - ./ssl/fullchain.pem:/etc/ssl/fullchain.pem

  alertmanager:
    image: prom/alertmanager:latest
    container_name: ps-alertmanager
    restart: unless-stopped
    networks:
      - prometheus
    ports:
      - 9093:9093
    volumes:
      - ./GAP-1/alertmanager.yml:/etc/alertmanager/alertmanager.yml

networks:
  webapp:
  prometheus:
